[package]
name = "sorttable-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
authors = ["Ziale"]

[dependencies]
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = { version = "2.0.98", features = ["full"] }
